# 오류 처리

C++ 에서는 예기치 않은 동작을 처리하는 두가지 주요 방법으로 단정(Assertion) 과 예외(Exception)가 잇다.

전자는 프로그래밍 오류를 감지하기 위한 방법이고, 후자는 프로그램의 적잘한 지속을 방해하는 예외적인 상황을 위한 방법이다.


> ### 단정(Assertion)

헤더 `<cassert>` 의 매크로 assert 는 C 에서 상속받은 매크로이지만 여전히 유효하다.

표현식을 계산한뒤, 결과가 false 면 즉시 프로그램을 종효한다. 

assert 는 프로그래밍 오류를 감지하는데 사용해야 한다.

```cpp
//음수가 아닌 실수의 제곱근을 계산
#include <iostream>
#include <cassert>

double square_root(double x)
{
    dheck_somehow(x >= 0);
    ...
    assert(result >= 0.0);

    return result;
}
```

첫줄에 잇는 검사 함수를 구현하는 방법은 잠시 미루어 두고, assert 의 결과가 false 라면

다음과 같은 오류를 출력한다.

____
assert_test : assert_test.cpp:10: double square_root (double):
Assertion 'result >= 0.0' falied.
___

assert 의 큰 장점은 간단한 매크로 선언만으로 오류를 완전히 사라지게 할수 있다는 점이다.

`<cassert>` 를 포함 하기 전에 NDEBUG 를 정의할수 있다.

```cpp
#define NDEBUG
#include <cassert>
```

이렇게 하면, 모든 단정을 비활성화 하며, 실행 파일에서 아무런 동작을 하지 않는다. 

디버그 모드와 릴리즈 모드를 번갈아 가며 전환 할때마다 프로그램 소르를 변경하는 대신, 컴파일러 플래그(/D)에 NDEBUG 를 선언하는게 더 낫다. 또한 코드도 더 깨끗하다.

```cpp
g++ my_cpp.cpp -o my_app -O3 -DNDEBUG
```

핵심 커널에 단정이 있는 소프트웨어는 릴리즈 모드에서 단정을 비활성화 하지 않을경우 2배이상 느려질수 있다. CMAKE 와 같은 좋은 빌드 시스템은 릴리즈 모드의 컴파일 플래그에 -DNDEBUG 를 자동으로 포함한다.

단정을 쉽게 비활성화 할수 있으므로, 다음 참고를 따르길 권한다

`
NOTE = 방어적 프로그래밍
최대한 많은 속성을 테스트하라.
`

구현을 위한 속성을 틀림없이 유지하고 있다고 확신 하더라도 단정을 작성하길 바란다.
때때로 우리가 가정한 것처럼 시스템이 정확하게 동작하지않거나, 드물지만 컴파일러에 버그가 있을수도 있다.

또는 원래 의도했던 것과 약간 다르게 구현 했을수도 있다.

대규모 테스트집합을 구현하면, 언젠가 생길 크래시에 모든 단정을 활성화 한 상태에서 

크래시의 원인을 찾는데 큰 도움이 된다. 

그러나 이렇게 하려면 크래시 상황을 재현할 수있어야 하며, 더 느린 디버그 모드의 프로그램이 적절한 시간 내에 크리티컬 섹션에 도달해야한다.

> ### 예외

1. 동기 부여

1. 옛날 스타일의 오류처리

컴퓨터 문제를 처리할 때 오류코드를 반환하는 방식이다. 

파일에서 행렬을 읽기위해 파일이 실제로 있는지 검사한다고 가정해 보자.

만약 파일이 없다면 오류코드 1 을 반환한다.

```cpp
int read_matrix_file(const chat* fnmae, ...)
{
    fstream f(fname)
    if(!f.open())
        return 1;
    ...
    return 0;
}
```

그래서 우리는 잘못 될수 있는 모든 경우에 대해 검사를수행하고 호출자에게 적절한 오류코드를 알려준다.

호출자가 오류를 확인 한뒤 적잘하게 반응하면 괜찮지만, 반환코드를 단순히 무시한다면 아무일도 일어나지 않게된다.

이 프로그램은 계속 실행되다가 나중에 불합리한 데이터로 인해 크래시가 발생할 수도 있고,

설상가상으로 무의미한 결과를 생성해 부주의한 사람들이 자동차나 비행기를 만드는데 사용할수도 있다.

오류코드의 또 다른 단점은 계산결과를 반환할 수 없으며, 레퍼런스 인수로 전달해야 한다는 점이다.

이렇게 하면 결과로 표현식을 만들 수 없다. 다른 방법은 결과를 반환하고 오류코드를 훨씬 덜 복잡한 레퍼런스 함수 인수로 전달 하는 방법이다.

2. Throw

더 나은 접근 법은 예외를 던지는 방법이다.

```cpp

martix read_marix_file(const char* fname, ...)
{
    fstream f(fname)
    if(!f.is_open())
    {
        throw * "Cannot open File";
        ...
    }
}
```

이 버전은 예외가 발생하며, 함수를 호출하는 애플리케이션은 이제 예외에 응답해야한다. 그렇지 않으면, 크래시가 발생한다.

오류 코드에 대한 예외 처리의 이점은 우리가 처리할 수있는 문제만 신경 쓰면 된다는점이다.

예를 들어 read_matrix_file 이라는 함수에서 존재하지 않는 파일을 처리하지 않을 수도 있다.

이경우 , 

예외가 발생하지 않으므로 코드를 실행한다. 따라서 우리는 오류코드를 반환해 프로그램을 난독화 할 필요가 없다.

예외가 발생한 경우 적절한 예외 처리로 전달한다. 이러한 처리는 우리의 시나리오에서 사용자가 새 파일을 요청하는 GUI 에 포함할 수있다. 

따라서 예외는 동신에 읽을수 있는 소스와 보다 안정적인 오류 처리로 이어진다.

C++ 를 사용하면 문자열, 숫자, 사용자 정의타입등 모든 타입을 예외로 처리할수 있지만,

에외타입을 정의하거나 표준 라이브러이 메소드를 사용하는게 좋다.

```cpp
struct cannot_open_file{};
void read_matrix_file(const char* fname,...)
{
    fstream f(fname);
    if(!f.is_open())
    {
        throw cannot_open_file{};
    }
    ...
}
```

여기에서는 사용자 정의 예외 타입을 도입했다. 이후 클래스 정의 방법을 자세히 설명한다.
위의 예제에서 여닫는 괄호만 있으면 되는 빈 클래스를 정의했다. 

더 큰 프로젝트에서는 대게 std::exception 에서 파생한 예외 타입의 전체 계층 구조를 확립한다.

> ### catch 

예외 상황에 대처하려면 예외를 붙잡아야한다. 이는 **try-catch 블록에서 수행한다.**

```cpp
try
{
    ..
}catch (e1_type& e1)
{
    ...
}catch (e2_type& e2)
{

}
```

우리가 해결할수 있는 문제를 기대 할때마다 try 블록을 연다. 닫는 중괄호 뒤에서 예외를 잡아낼수 있고, 예외의 타입과 가능하면 그값에 따라 복구를 시작할수 있다.

특히 [타형성타입] 이 연관되어 있을때, 레퍼런스를 통해 예외를 잡기 권한다.

예외가 발생하면 일치하는 타입을 갖는 첫번째 catch 블록을 실행한다.

동일한 타입의 추가 catch 블록은 무시한다. 말줄임표(...) 가 있는 catch 블록은 모든 에외를 잡는다.

```cpp
try
{
    ..
}catch (e1_type& e1)
{
    ...
}catch (e2_type& e2)
{

}catch(...) // 다른 모든 예외를 처리
```

물론 모든 예외를 잡는 catch 는 마지막에 와야한다.


```cpp
//0으로 나누는 나눗셈
//try-catch 예제

#include <class.h>

int main()
{
    int lvalue = 8;
    int rvalue = 0;

    try{
        if(rvalue == 0 && rvalue < 0)
            throw 'rvalue';

        int result = lvalue / rvalue;

        std::cout << "result " << result << endl; 
    }
    catch(char ext)
    {
        cout << ext << "의 수치 재설정" << endl;

    }
    return 0;
}
```

```cpp

try{
    read_matrix_file("does_not_exist.dat");
}catch (cannot_open_file& e)
{
    cerr << "Hey guys, your file is not exist! i'm out!\n";
    exit(EXIT_FAILURE);
}
```

예외를 잡으면 문제가 해결됐다고 간주하고 catch 블록 이후 부터 실행을 게속한다. 실행을 종료하기 위해 `<cstdlib>` 헤더에서 exit  를 사용했다. 

exit  함수는 main 함수에 없는 경우에도 실행을 종료한다. **이 함수는 이후 실행이 너무 위험하거나 호출하는 함수에 예외에 대한 해결책이 없을 때만 사용해야한다.**

또는 나중에 처리할 수 있는 예외를 다시 던져 문제가 되는 부분을 알리거나 부분적인 복구 조치를 계속할 수 있다.

```cpp 
try{
    read_matrix_file("does_not_exist.dat")
    
}catch (cannot_open_file& e)
{
    cerr << "file is not there!, caller help me"
    throw e;
}
```

우리의 경우, 이미 main 함수에 있고 호출 스택에 에외를 잡는 다른 함수가 없다. 이예외를 다시 던질수 있는 더 짧은 표기법이 있다.

```cpp
}catch (cannot_open_file& e)
{
    ...

    throw;
}
```

이 표기법은 오류가 발생하기 쉽고 원래의 예외를 다시 던진다는 것을 보다 분명하게 보여주기 때문에 선호하는 표기번이다. 빈블록을 사용하면 예외를 무시할 수 있다.

```cpp
} catch(cannot_open_file&){} // 쓰레기 파일. 계속 실행한다.
```

지금 까지 우리의 예외 처리는 실제로 파일 누락 문제를 해결하지 못했었다. 

사용자가 파일 이름을 제공하면 우리를 행복하게 해주는 파일이름을 줄때 까지 계속해서 조를수있다.

```cpp
bool keep_trying = true;
do
{
    std::string fname;
    cout << "Plz enter the file name" << endl;
    cin << fname;

    try
    {
        read_matrix_file(fname);
        ...
        keep_trying = false;
    }
    catch (cannot_open_file& e)
    {
        cout << "could not open file. try another one !" << endl;
    }
    catch (..)
    {
        cout << "Something is fishy here Try another File" << endl;
    }
}
while (keep_trying);
```

try 블록의 끝에 도달했을 때, 아무 예외도 발생하지 않았으므로 이제 끝마쳐도 될것같다.

그렇지 않으면, catch 블록중 하나에 도착해 kepp_trying 이 true 로 유지한다.

예외의 큰 장점은 오류가 발견된 상황에서 당장 처리할수 없는 문제를 나중으로 미룰 수 있다는 점이다. 

> ### 누가 던지는가?

C++11 에서는 함수에서 예외를 던지지 않아야 한다는 걸 지정하는 새로운 지정자를 추가했다.

```cpp
double square_root(double x) noexcept {...}
```

이 지정자의 장점은 호출 코드가 square_root 호출 후에 던진 예외를 확인 하지 않아도 된다는 점이다.

만약 지정자를 추가했음에도 불구하고 에외가 발생하면 프로그램을 종료한다.

템플릿 함수에서는 예외가 발생했는지 여부에 따라 상관없이 인수타입에 의존할 수있다.

이를 올바르게 처리하기 위해 noexcept 는 컴파일 타입 조건에 의존할수있다 [참고]

단정 또는 예외가 바람직 한지 아닌지는 쉬운 질문이 아니며,

대답 또한 간단하지 않다. [참고2] 를 읽고 직접 생각해보길 바란다.

[noexcept참고](http://egloos.zum.com/sweeper/v/3148916)
____
**<C++11>**
정적 단정(static_assert)

컴파일 과정에서 감지할 수 잇는 프로그램 오류는 static_assert 를 발생 시킬 수 있다.

이 경우, 오류메시지를 표시하고 컴파일을 중단한다. [참고3] 
___

